### ISSUE TITLE
Populate CI with DockerHub credentials

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/reverse-proxy#1]
Deploying the image to docker hub has been done using CircleCI, which requires authentication. Some credentials need to be provided to upload the container.

(I assume in the past these have been @jimmythompson 's credentials?)

**Comment by RealOrangeOne** [comment]
As an aside to this, it might be nice to try out the [GitHub Docker package registry](https://help.github.com/en/articles/configuring-docker-for-use-with-github-package-registry), or add more people to the Docker Org? (cc @jimmythompson )

**Comment by jimmythompson** [comment]
Github would be better, then you can just amend the kubernetes stuff to point to it. It then wipes out a whole different vendor. 👍

**Comment by PeterJCLaw** [comment]
The GitHub Docker package repository seems to still be coupled to personal access tokens, which means that we're still left with the conundrum of a single point of failure around the person whose token we're using.

Is there a way that we can use credentials which are attached to our GitHub org, rather than a person?

**Comment by RealOrangeOne** [comment]
It would appear not.

> Using the docker command, you can authenticate to GitHub Package Registry using your GitHub username and a personal access token

https://help.github.com/en/articles/configuring-docker-for-use-with-github-package-registry#authenticating-to-github-package-registry

A way to solve this would be to create a bot user which can upload images. 

Alternatively, Docker Hub can be linked to a repo, and automatically build a docker container off a specific branch, which might be a better way of implementing this? Then CI is simply a way of testing the image builds, rather than also uploading it.

**Comment by PeterJCLaw** [comment]
I guess an alternative might be to ensure that we have multiple people who have access to the registry, which mostly removes the SPOF as we can swap out the credentials in Circle at any point anyway.

**Comment by PeterJCLaw** [comment]
(I think I had also assumed that there were ways for collaborators to extract credentials from CircleCI, but I think they'd need to be trying quite hard to do that)

**Comment by jimmythompson** [comment]
From what I understand, you can only publish to `srobo/reverse-proxy` if you have the rights to push to this Github repository.

As long as that's true, I think it's fine to use a personal access token. If someone leaves/revokes the token/are removed from the org it'll flare up pretty quickly and we drop in another token.

**Comment by jimmythompson** [comment]
This is done right?

**Comment by PeterJCLaw** [comment]
Yeah, I think you did this.
